workspace(name = "Edison")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "com_github_marpaia_alpaca_trade_api_cpp",
    strip_prefix = "alpaca-trade-api-cpp-master",
    urls = ["https://github.com/aidanjalili/alpaca-trade-api-cpp/archive/master.tar.gz"]
    #Should prolly add a sha later/when released for security
    #OR not who cares fuck security
)
load("@com_github_marpaia_alpaca_trade_api_cpp//bazel:deps.bzl", "alpaca_deps")
alpaca_deps()

#For boost
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "com_github_nelhage_rules_boost",
    commit = "1e3a69bf2d5cd10c34b74f066054cd335d033d71",
    remote = "https://github.com/nelhage/rules_boost",
    shallow_since = "1591047380 -0700",
)

load("@com_github_nelhage_rules_boost//:boost/boost.bzl", "boost_deps")
boost_deps()

new_local_repository(
    name = "python_linux",
    path = "/usr",
    build_file_content = """
cc_library(
    name = "python38-lib",
    srcs = ["lib/python3.8/config-3.8m-x86_64-linux-gnu/libpython3.8.so"],
    hdrs = glob(["include/python3.8/**/*.h"]),
    includes = ["include/python3.8"],
    visibility = ["//visibility:public"]
)
    """
)